<?php

const ROOT_DIR = __DIR__;
const PYTHON_SHELL_NAME = "python3";
const CERTIFICATE_GENERATOR_DIR = ROOT_DIR . "/html_to_pdf";
const CERTIFICATE_PY_FILE = CERTIFICATE_GENERATOR_DIR . "/index.py";
const CERTIFICATE_OUTPUT = CERTIFICATE_GENERATOR_DIR . "/output.pdf"; 